### ISSUE TITLE
Change URL in description

### ISSUE THREAD

**Issue by melodykramer** [18F/automated-testing-playbook#12]
No rush, but the new URL is https://pages.18f.gov/automated-testing-playbook/

:+1: :+1: 

I don't have access or I would do this! :facepunch:

**Comment by mbland** [comment]
@melodykramer I think you should be able to give this a go now, if you're up for it.

**Comment by melodykramer** [comment]
Don't think I have access yet!

**Comment by mbland** [comment]
D'oh! Has to do with repo ownership, not just who can collaborate, apparently. I also didn't realize what you were asking 'til you showed me. :-) Fixed, and thanks for the catch!
